[package]
name = "webassembly_android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Dépendances de base
jni = "0.21"
android_logger = "0.13"
log = "0.4"

# Ajout progressif des dépendances serveur
tokio = { version = "1.0", features = ["rt", "net", "macros", "time"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"], default-features = false }

# Dépendances locales du serveur avec features nécessaires
server = { path = "../../server", features = ["sqlite"] }
core = { path = "../../core", features = ["sqlite"] }
