[package]
name = "webassembly_android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
android_logger = "0.13"
log = "0.4"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Ajout des dépendances du serveur
actix-web = { version = "4", features = ["rustls-0_22"] }
actix-files = "0.6"
actix-cors = "0.6"
anyhow = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "uuid", "chrono"] }
url = "2"
dotenv = "0.15"
uuid = { version = "1.4", features = ["v4", "serde"] }
env_logger = "0.10"
futures = "0.3"
actix-multipart = "0.6"
rustls = "0.22"
rustls-pemfile = "2.0"
rcgen = "0.12"

[dependencies.core]
path = "../../core"

[dependencies.server]
path = "../../server"

[target.'cfg(target_os = "android")'.dependencies]
android-activity = { version = "0.5", features = ["native-activity"] }
