[alias]
master = "exec -- cmd /c \"cd client & wasm-pack build --target web --out-dir static/pkg & cd .. & cargo run\""
build-wasm = "exec -- cmd /c \"cd client & wasm-pack build --target web --out-dir static/pkg\""

